version: '3.9'

services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=stationDB
      - MYSQL_DATABASE=daily_records
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql_data:/var/lib/mysql
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=db
      - MYSQL_ROOT_PASSWORD=stationDB
    depends_on:
      - db

  backend:
    build:
      context: ./la-estacion-backend
      dockerfile: Dockerfile
    image: draifor/laestacionbackend:v1
    restart: always
    ports:
      - 5000:3000
    environment:
      - PORT=3000
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DIALECT=mysql
      - DB_USERNAME=root
      - DB_PASSWORD=stationDB
      - DB_NAME=daily_records
      - JWT_SECRET=stationDB
    volumes:
      - ./la-estacion-backend/src:/app/src
    depends_on:
      - db
